package progressbar;

/**
 *
 * @author davibern
 * @version 1.0
 */
public class ProgressBarPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProgressBarPanel
     */
    public ProgressBarPanel() {
        initComponents();
        mostrarValores();
    }
    
    public Rangos getSelectedValue() {
        return new Rangos(this.jSliderNivel1.getValue(), this.jSliderNivel2.getValue());
    }
    
    public void mostrarValores() {
        this.jLabelNivel1.setText(String.valueOf(this.jSliderNivel1.getValue()) + "%");
        this.jLabelNivel2.setText(String.valueOf(this.jSliderNivel2.getValue()) + "%");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRango1 = new javax.swing.JLabel();
        jLabelRango2 = new javax.swing.JLabel();
        jSliderNivel1 = new javax.swing.JSlider();
        jSliderNivel2 = new javax.swing.JSlider();
        jLabelNivel1 = new javax.swing.JLabel();
        jLabelNivel2 = new javax.swing.JLabel();

        jLabelRango1.setText("Rango 1");

        jLabelRango2.setText("Rango 2");

        jSliderNivel1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderNivel1StateChanged(evt);
            }
        });

        jSliderNivel2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderNivel2StateChanged(evt);
            }
        });

        jLabelNivel1.setText("35 %");

        jLabelNivel2.setText("75 %");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelRango1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSliderNivel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelRango2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSliderNivel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNivel1)
                    .addComponent(jLabelNivel2)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelRango1)
                    .addComponent(jSliderNivel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNivel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelRango2)
                    .addComponent(jSliderNivel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNivel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderNivel1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderNivel1StateChanged
        if (this.jSliderNivel1.getValue() >= this.jSliderNivel2.getValue()) {
            this.jSliderNivel2.setValue(this.jSliderNivel1.getValue());
        }
        mostrarValores();
    }//GEN-LAST:event_jSliderNivel1StateChanged

    private void jSliderNivel2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderNivel2StateChanged
        if (jSliderNivel2.getValue() <= jSliderNivel1.getValue()) {
            jSliderNivel1.setValue(jSliderNivel2.getValue());
        }
        mostrarValores();
    }//GEN-LAST:event_jSliderNivel2StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelNivel1;
    private javax.swing.JLabel jLabelNivel2;
    private javax.swing.JLabel jLabelRango1;
    private javax.swing.JLabel jLabelRango2;
    private javax.swing.JSlider jSliderNivel1;
    private javax.swing.JSlider jSliderNivel2;
    // End of variables declaration//GEN-END:variables
}
